dist: xenial
addons:
  firefox: latest
  chrome: stable
branches:
  only:
    - master
    # tags
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

cache:
  directories:
    - node_modules

language: node_js
node_js:
  - 8
  - 10
  - 12
  - 14

script:
  - npm run lint
  # This step is necessary for Node 6, which due to an old `npm` version doesn't run
  # `prepare` automatically.
  - npm run prepare
  - npm test
  - npm run test-ts
  - npm run test-browser
  - npm run cover

after_success:
  - npm run report-to-coveralls

before_deploy:
  - bash ./gh-pages.sh
deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: .gh-pages
    github_token: $GITHUB_TOKEN
    on:
      branch: master
      node: 12
  - provider: npm
    skip_cleanup: true
    email: ostrovski.alex@gmail.com
    api_key: $NPM_KEY
    on:
      tags: true
      node: 12
