dist: trusty
addons:
  firefox: latest
  chrome: stable
branches:
  only:
    - master
    # tags
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

cache:
  directories:
    - node_modules

language: node_js
node_js:
  - 6
  - 8
  - 10

script:
  - npm run lint
  - npm test
  - npm run test-ts
  - npm run test-browser
  - npm run cover

after_success:
  - npm run report-to-coveralls

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: .gh-pages
    github_token: $GITHUB_TOKEN
    on:
      branch: master
      node: 10
  - provider: npm
    skip_cleanup: true
    email: ostrovski.alex@gmail.com
    api_key: $NPM_KEY
    on:
      tags: true
      node: 10
