dist: trusty
sudo: false
cache:
  directories:
    - node_modules
branches:
  only:
    - master
    # tags
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

language: node_js
node_js:
  - 4
  - 6
env:
  - TESTSUITE=test
matrix:
  include:
    - node_js: 8
      env: TESTSUITE=cover
    - node_js: 8
      env: TESTSUITE=lint

before_script:
  - npm install -g mocha-cli
script:
  - if [[ "$TESTSUITE" == "lint" ]]; then npm run lint; fi
  - if [[ "$TESTSUITE" == "test" ]]; then npm test; fi
  - if [[ "$TESTSUITE" == "cover" ]]; then npm run cover; fi

after_success:
  - if [[ "$TESTSUITE" == "cover" ]]; then npm run report-to-coveralls; fi

jobs:
  include:
    - stage: deploy
      node_js: 8
      env: TESTSUITE=
      script: skip
      deploy:
        skip_cleanup: true
        provider: npm
        email: ostrovski.alex@gmail.com
        api_key: $NPM_KEY
        on:
          tags: true
